"""
Sample test data for API testing
These are example flows from CIC-IDS2017 dataset
"""

# Sample BENIGN flow
SAMPLE_BENIGN = {
    "Destination Port": 80,
    "Flow Duration": 119,
    "Total Fwd Packets": 6,
    "Total Length of Fwd Packets": 214,
    "Fwd Packet Length Max": 163,
    "Fwd Packet Length Min": 0,
    "Fwd Packet Length Mean": 35.66666667,
    "Fwd Packet Length Std": 64.12215118,
    "Bwd Packet Length Max": 0,
    "Bwd Packet Length Min": 0,
    "Bwd Packet Length Mean": 0,
    "Flow Bytes/s": 1798319.328,
    "Flow Packets/s": 50420.16807,
    "Flow IAT Mean": 23.8,
    "Flow IAT Std": 26.75343572,
    "Flow IAT Max": 68,
    "Flow IAT Min": 0,
    "Fwd IAT Mean": 23.8,
    "Fwd IAT Std": 26.75343572,
    "Fwd IAT Min": 0,
    "Bwd IAT Total": 0,
    "Bwd IAT Mean": 0,
    "Bwd IAT Std": 0,
    "Bwd IAT Max": 0,
    "Bwd IAT Min": 0,
    "Fwd PSH Flags": 0,
    "Fwd URG Flags": 0,
    "Fwd Header Length": 120,
    "Bwd Header Length": 0,
    "Bwd Packets/s": 0,
    "Min Packet Length": 0,
    "Max Packet Length": 163,
    "Packet Length Mean": 35.66666667,
    "Packet Length Variance": 4111.650794,
    "FIN Flag Count": 0,
    "RST Flag Count": 0,
    "PSH Flag Count": 0,
    "ACK Flag Count": 0,
    "URG Flag Count": 0,
    "Down/Up Ratio": 0,
    "Init_Win_bytes_forward": 8192,
    "Init_Win_bytes_backward": 0,
    "act_data_pkt_fwd": 3,
    "min_seg_size_forward": 20,
    "Active Mean": 0,
    "Active Std": 0,
    "Active Max": 0,
    "Active Min": 0,
    "Idle Mean": 0,
    "Idle Std": 0
}

# Sample DDoS attack flow
SAMPLE_DDOS = {
    "Destination Port": 80,
    "Flow Duration": 0,
    "Total Fwd Packets": 1,
    "Total Length of Fwd Packets": 0,
    "Fwd Packet Length Max": 0,
    "Fwd Packet Length Min": 0,
    "Fwd Packet Length Mean": 0,
    "Fwd Packet Length Std": 0,
    "Bwd Packet Length Max": 0,
    "Bwd Packet Length Min": 0,
    "Bwd Packet Length Mean": 0,
    "Flow Bytes/s": 0,
    "Flow Packets/s": 0,
    "Flow IAT Mean": 0,
    "Flow IAT Std": 0,
    "Flow IAT Max": 0,
    "Flow IAT Min": 0,
    "Fwd IAT Mean": 0,
    "Fwd IAT Std": 0,
    "Fwd IAT Min": 0,
    "Bwd IAT Total": 0,
    "Bwd IAT Mean": 0,
    "Bwd IAT Std": 0,
    "Bwd IAT Max": 0,
    "Bwd IAT Min": 0,
    "Fwd PSH Flags": 0,
    "Fwd URG Flags": 0,
    "Fwd Header Length": 20,
    "Bwd Header Length": 0,
    "Bwd Packets/s": 0,
    "Min Packet Length": 0,
    "Max Packet Length": 0,
    "Packet Length Mean": 0,
    "Packet Length Variance": 0,
    "FIN Flag Count": 0,
    "RST Flag Count": 0,
    "PSH Flag Count": 0,
    "ACK Flag Count": 0,
    "URG Flag Count": 0,
    "Down/Up Ratio": 0,
    "Init_Win_bytes_forward": 1024,
    "Init_Win_bytes_backward": 0,
    "act_data_pkt_fwd": 0,
    "min_seg_size_forward": 20,
    "Active Mean": 0,
    "Active Std": 0,
    "Active Max": 0,
    "Active Min": 0,
    "Idle Mean": 0,
    "Idle Std": 0
}

# Sample Port Scan flow
SAMPLE_PORTSCAN = {
    "Destination Port": 22,
    "Flow Duration": 3,
    "Total Fwd Packets": 2,
    "Total Length of Fwd Packets": 0,
    "Fwd Packet Length Max": 0,
    "Fwd Packet Length Min": 0,
    "Fwd Packet Length Mean": 0,
    "Fwd Packet Length Std": 0,
    "Bwd Packet Length Max": 0,
    "Bwd Packet Length Min": 0,
    "Bwd Packet Length Mean": 0,
    "Flow Bytes/s": 0,
    "Flow Packets/s": 666666.6667,
    "Flow IAT Mean": 3,
    "Flow IAT Std": 0,
    "Flow IAT Max": 3,
    "Flow IAT Min": 3,
    "Fwd IAT Mean": 3,
    "Fwd IAT Std": 0,
    "Fwd IAT Min": 3,
    "Bwd IAT Total": 0,
    "Bwd IAT Mean": 0,
    "Bwd IAT Std": 0,
    "Bwd IAT Max": 0,
    "Bwd IAT Min": 0,
    "Fwd PSH Flags": 0,
    "Fwd URG Flags": 0,
    "Fwd Header Length": 40,
    "Bwd Header Length": 0,
    "Bwd Packets/s": 0,
    "Min Packet Length": 0,
    "Max Packet Length": 0,
    "Packet Length Mean": 0,
    "Packet Length Variance": 0,
    "FIN Flag Count": 0,
    "RST Flag Count": 1,
    "PSH Flag Count": 0,
    "ACK Flag Count": 1,
    "URG Flag Count": 0,
    "Down/Up Ratio": 0,
    "Init_Win_bytes_forward": 1024,
    "Init_Win_bytes_backward": 0,
    "act_data_pkt_fwd": 0,
    "min_seg_size_forward": 20,
    "Active Mean": 0,
    "Active Std": 0,
    "Active Max": 0,
    "Active Min": 0,
    "Idle Mean": 0,
    "Idle Std": 0
}

# All samples for batch testing
ALL_SAMPLES = [
    {"name": "BENIGN", "data": SAMPLE_BENIGN},
    {"name": "DDoS", "data": SAMPLE_DDOS},
    {"name": "Port Scan", "data": SAMPLE_PORTSCAN},
]